#!/bin/sh

if [ ! -d "pcf" ];then
    mkdir pcf
fi

# Remove old files
rm -f pcf/*.pcf pcf/*.bdf.bak

# Create PCF fonts
for file in *.bdf; do
    bdftopcf -o "pcf/${file%\.*}.pcf" "$file"
done

# Create X font register files
xset fp rehash
